matrix:
  include:
    - language: c

      compiler:
        - gcc
        - clang

      before_script:
        - $TRAVIS_COMPILER -Wall -I./ main_test.c -pthread -o test

      script:
        - ./test

    - language: c++

      compiler:
        - g++
        - clang++

      before_script:
        - $TRAVIS_COMPILER -Wall -std=c++11 -I./ MainTest.cpp -pthread -o test

      script:
        - ./test

notifications:
  email:
    - minikawoon99@gmail.com